CREATE TABLE `auditLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`caseId` int,
	`action` varchar(100) NOT NULL,
	`entityType` varchar(50) NOT NULL,
	`entityId` int NOT NULL,
	`oldValues` text,
	`newValues` text,
	`changedFields` text,
	`ipAddress` varchar(45),
	`userAgent` text,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `caseInteractions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`userId` int NOT NULL,
	`type` enum('status_change','deadline_added','deadline_updated','deadline_removed','movement_added','document_uploaded','note_added','client_contacted','court_contacted','hearing_scheduled','hearing_completed','appeal_filed','settlement_proposed','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`relatedDeadlineId` int,
	`relatedMovementId` int,
	`relatedDocumentId` int,
	`metadata` text,
	`attachments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `caseInteractions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `courtData` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`userId` int NOT NULL,
	`courtName` varchar(255),
	`courtCode` varchar(50),
	`vara` varchar(100),
	`judge` varchar(255),
	`processStatus` enum('pending','active','suspended','archived','closed','appealed','unknown') NOT NULL DEFAULT 'unknown',
	`lastMovement` text,
	`lastMovementDate` timestamp,
	`plaintiff` text,
	`defendant` text,
	`plaintiffLawyer` varchar(255),
	`defendantLawyer` varchar(255),
	`nextHearingDate` timestamp,
	`nextHearingLocation` varchar(500),
	`nextHearingType` varchar(100),
	`courtMetadata` text,
	`externalId` varchar(255),
	`lastSyncAt` timestamp,
	`syncStatus` enum('synced','pending','failed','manual') NOT NULL DEFAULT 'manual',
	`syncErrorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `courtData_id` PRIMARY KEY(`id`),
	CONSTRAINT `courtData_externalId_unique` UNIQUE(`externalId`)
);
--> statement-breakpoint
CREATE TABLE `tribunalSyncConfig` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tribunalName` varchar(255) NOT NULL,
	`tribunalCode` varchar(50) NOT NULL,
	`apiUrl` varchar(500) NOT NULL,
	`apiKey` varchar(255),
	`apiSecret` varchar(255),
	`authMethod` enum('api_key','oauth','basic_auth','custom') NOT NULL DEFAULT 'api_key',
	`isEnabled` boolean NOT NULL DEFAULT true,
	`autoSyncEnabled` boolean NOT NULL DEFAULT true,
	`syncIntervalMinutes` int NOT NULL DEFAULT 360,
	`lastSyncAt` timestamp,
	`nextSyncAt` timestamp,
	`lastErrorAt` timestamp,
	`lastErrorMessage` text,
	`consecutiveFailures` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tribunalSyncConfig_id` PRIMARY KEY(`id`)
);
